name: Deploy LMS Backend to Azure

on:
  push:
    branches:
      - dev

jobs:
  build-and-deploy:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET 8
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restore
        run: dotnet restore LMS.API/LMS.API.csproj

      - name: Build
        run: dotnet build LMS.API/LMS.API.csproj --configuration Release --no-restore

      - name: Publish
        run: dotnet publish LMS.API/LMS.API.csproj --configuration Release --output ./publish

      - name: Deploy to Azure App Service
        uses: azure/webapps-deploy@v3
        with:
          app-name: LMSAPI20260528173411
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: ./publish